= Variscite BSP Plus NWA Specifics

= Run a script that will do most setup for you

Download nwasetup from scripts and put somewhere in your path
[source,console]
$: mkdir -p some/dir/to/work/in
$: cd some/dir/to/work/in
$: nwasetup

The script will

* Download development packages necessary for yocto to run your host
* Remind you to setup git username and email settings if not yet set up
* Download repo if it is not found in your path
* Run repo init and sync on the manifest in this repo
** NOTE: it downloads the latest, if you want a specific version you will need to change the script

Once the script is finished you should find yourself in a directory
called nwa-var-fslc-yocto.
From there you can source a setup file called SOURCEME that will do some
setup and put in in a build file.
From there you can build an image:
[source,console]
$: . ./SOURCEME
...
$: bitbake fsl-image-gui

Once that is finished there will be an sdcard image file in
tmp/deploy/images/imx6ul-var-dart/fsl-image-gui-imx6ul-var-dart-<DATESTRING>.sdcard.
You can dd that to an sdcard and boot your dart board.

