= Variscite BSP Plus NWA Specifics

= Run a script that will do most setup for you

Download nwasetup from scripts and put somewhere in your path
[source,console]
$: mkdir -p some/dir/to/work/in
$: cd some/dir/to/work/in
$: nwasetup

The script will

* Download a bunch of useful development packages
* Remind you to setup git username and email settings if not yet set up
* Download repo if it is not found in your path
* Run repo init and sync on the manifest in this repo

Or do the original Variscite thing

= Original Variscite Release Notes

This branch is based on 

* Poky: yocto-2.4 (rocko-18.0.0)
* FSL Community BSP: rocko
* QT: 5.9.2

= Variscite BSP Platform

To get the BSP you need to have `repo` installed and use it as:

Install the `repo` utility:

[source,console]
$: mkdir ~/bin
$: curl http://commondatastorage.googleapis.com/git-repo-downloads/repo > ~/bin/repo
$: chmod a+x ~/bin/repo

Download the BSP source:

[source,console]
$: PATH=${PATH}:~/bin
$: mkdir ~/var-fslc-yocto
$ cd ~/var-fslc-yocto
$ repo init -u https://github.com/jcrigby/nwa-variscite-bsp-platform.git -b rocko
$ repo sync -j4

At the end of the commands you have every metadata you need to start work with.

To start a simple image build:

[source,console]
$: MACHINE=<machine> DISTRO=<distro> source ./setup-environment <build directory>
$: bitbake core-image-base

You can use any directory to host your build.

The source code is checked out at `var-fslc-yocto/sources`.
